version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/lucy
    steps:
      - checkout
      - restore_cache:
          keys:
            - lucy-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - lucy-{{ .Branch }}
            - lucy-master
      - run: yarn install
      - save_cache:
          key: lucy-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
      - run: npx react-native run-ios --configuration Release
      - store_artifacts:
          path: lucy/ios/build/Build/Products/Release-iphonesimulator
          destination: lucy-build
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/lucy
      - run:
          name: Deploy to TestFlight
          command: |
            fastlane beta
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
              # hello