version: 2.1
jobs:
  build:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    environment:
      EXPO_CLI_USERNAME: jamajosa
      EXPO_CLI_PASSWORD: Basje!23
      EAS_ANDROID_APP_ID: com.jamajosa.Lucy
      EAS_ANDROID_KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
      EAS_ANDROID_KEY_ALIAS: $KEY_ALIAS
      EAS_ANDROID_KEY_PASSWORD: $KEY_PASSWORD
      EAS_ANDROID_FULL_NAME: $FULL_NAME
      EAS_ANDROID_ORG_UNIT: $ORG_UNIT
      EAS_ANDROID_ORG_NAME: $ORG_NAME
      EAS_ANDROID_CITY: $CITY
      EAS_ANDROID_STATE: $STATE
      EAS_ANDROID_COUNTRY_CODE: $COUNTRY_CODE
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Log in to Expo
          command: npx expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
      - run:
          name: Build project
          command: npx eas build -p android --skip-credentials-check
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test project
          command: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build