version: 2.1
jobs:
  build:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    environment:
      EXPO_CLI_USERNAME: jamajosa
      EXPO_CLI_PASSWORD: Basje!23
      EAS_ANDROID_APP_ID: com.jamajosa.Lucy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Log in to Expo
          command: npx expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
      - run:
          name: Build project
          command: EAS_ANDROID_APP_ID=com.jamajosa.Lucy npx eas build -p android
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test project
          command: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build