version: 2
jobs:
  build:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test project
          command: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build