version: 2.1
jobs:
  build:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npx eas build -p android --profile development
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/lucy
    docker:
      - image: circleci/node:14.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test project
          command: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build