version: 2.1
jobs:
  build:
    platform: android
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build APK
          command: |
            cd android && ./gradlew assembleRelease
      - persist_to_workspace:
          root: android/app/build/outputs
          paths:
            - apk
  deploy:
    requires:
      - build
    filters:
      tags:
        only: /^v[0-9].*$/
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Expo CLI
          command: yarn global add expo-cli
      - run:
          name: Publish to Expo
          command: |
            expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            expo publish --release-channel ${CIRCLE_TAG:1} --non-interactive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9].*$/
          environment:
            EXPO_USERNAME: jamajosa
            EXPO_PASSWORD: Basje!23
    # platform: android
    # publish: false