on: [push]
jobs:
  react_native_ci_job:
    runs-on: ubuntu-latest
    name: React Native CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: React Native CI
        uses: aslamanver/react-native-docker@v1
      - name: Install NPM Dependencies
        run: npm install
      - name: RUN EAS INSTALL
        run: npm i eas-cli
       - name: Set up Expo
        env:
          EXPO_TOKEN: ${{ secrets.EAS_BUILD_TOKEN }}
        run: |
          expo login --non-interactive --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}
          expo whoami
      - name: Run NX Dev Android Build
        run: npx eas-cli build --platform all --non-interactive